// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGjmyC71EjMQufm_sfWrxwFm1Tj7PQ-bg',
    appId: '1:727559699717:web:b7ffbfa5fcb6d2d74d4b6c',
    messagingSenderId: '727559699717',
    projectId: 'doctro-patient-app',
    authDomain: 'doctro-patient-app.firebaseapp.com',
    storageBucket: 'doctro-patient-app.firebasestorage.app',
    measurementId: 'G-T6V5X4Q310',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOt94aW5GZqMQD44FdY8TAVWy-6GT6crc',
    appId: '1:727559699717:android:aeffbb388cf5e5a34d4b6c',
    messagingSenderId: '727559699717',
    projectId: 'doctro-patient-app',
    storageBucket: 'doctro-patient-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDswjuCBt5FizGLDEeOEK-10gtI-htByQw',
    appId: '1:727559699717:ios:f8f56e3c8c4573194d4b6c',
    messagingSenderId: '727559699717',
    projectId: 'doctro-patient-app',
    storageBucket: 'doctro-patient-app.firebasestorage.app',
    iosBundleId: 'com.example.ffFiretodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGjmyC71EjMQufm_sfWrxwFm1Tj7PQ-bg',
    appId: '1:727559699717:web:eaee42e276212e974d4b6c',
    messagingSenderId: '727559699717',
    projectId: 'doctro-patient-app',
    authDomain: 'doctro-patient-app.firebaseapp.com',
    storageBucket: 'doctro-patient-app.firebasestorage.app',
    measurementId: 'G-P5KYQM16N6',
  );
}
